### DISCUSSION TITLE
Docker

### DISCUSSION THREAD

**Discussion by willkotheimer** [Ascend-Apollo-Apprentice-2024/learning-platform-api#52] [General]
## DockerCompose.yml file (with description):

- Each of these `services` (db, api, nginx, client, etc), represent individual docker containers that are created when the user or system runs `docker compose up`

```
services:
  db:  ## service type
    image: postgres:13   ## program:version
    container_name: postgres_container  ## name of docker container (arbitrary)
    restart: always ##  (will restart unless the container is explicitly stopped or removed. Will restart on error, on system reboot, or docker 
                            ## compose up)
    environment: ## variables used by postgres to set up the root postgres user
      POSTGRES_DB: learnopsdev
      POSTGRES_USER: learnopsdev
      POSTGRES_PASSWORD: ascend
    ports:  ## "External port : Internal Postgres Port" (External port needs to match the port that will be listened on other services) 
      - "5432:5432"
    volumes:  ## place where postgres data is stored in memory. postgres_data is the directory where data is stored, and this is mounted to:
                   ## /var/lib/postgresql/data which is the directory that postgres references.
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .     ## build looks for a dockerfile in the current directory and uses it to build the container.   . is the current directory.
    container_name: django_api   ## arbitary container name
    restart: always  ## container restarts unless otherwise told to stop
    environment:  ## 1st three variables used to connect with the database.
      LEARN_OPS_DB: learnopsdev
      LEARN_OPS_USER: learnopsdev
      LEARN_OPS_PASSWORD: ascend
      LEARN_OPS_HOST: db  # db is the name of the service and this uses the service name not the container's name
      LEARN_OPS_PORT: 5432  ## eternal port that postgres has exposed.
      CLIENTID: ${CLIENTID}   ## two variables that are found in the .env file and passed down to the entrypoint.sh file in the dockerfile
      SECRETKEY: ${SECRETKEY}
    depends_on:  ## these services must be up and running before this container can start
      - db
      - nginx
    expose:  
      - "8000"  ## port that this container allows traffic on from the host machine
    command: >   ## command overrides the CMD command in the dockerfile. The build uses original CMD, but  container start, it uses this one
      sh -c "python manage.py migrate &&  ## Applies any new database migrations
             python manage.py loaddata socialaccount.json &&   ## Loads predefined data from socialaccount.json into the database
             python manage.py loaddata complete_backup.json && ## Loads additional data from complete_backup.json
             gunicorn LearningPlatform.wsgi:application --bind 0.0.0.0:8000"  ## serves the django app and binds it to port 80
    env_file: ## defines the location of the .env file where the CLIENTID and SECRETKEY are located
      - .env
      
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  client:
    build:
      context: ../learning-platform-client
    container_name: learning_platform_client
    restart: always
    ports:
      - "3000:80"  # Exposes port 3000 for the client, mapped to Nginx in the container
    depends_on:
      - api
    networks:
      - default  # Ensure the client can communicate with the api and db services

volumes:
  postgres_data:

networks:
  default:
    driver: bridge

```

## API `dockerfile` (with description):

```
# Use official Python image
FROM python:3.9.0

# # Set environment variables
# ENV PYTHONUNBUFFERED=1
# ENV LEARN_OPS_DB=defaultdb
# ENV LEARN_OPS_USER=doadmin
# ENV LEARN_OPS_PASSWORD=AVNS_a-QoiCj6MfGqjcg7wO8
# ENV LEARN_OPS_HOST=learn-ops-prod-apollo-ascend-do-user-18311930-0.d.db.ondigitalocean.com
# ENV LEARN_OPS_PORT=25060

# Set the working directory
WORKDIR /app    ## docker creates the working directory app

# Install system dependencies (including Nginx)
RUN apt-get update && apt-get install -y \     ## RUN runs a bash script
    nginx \
    && rm -rf /var/lib/apt/lists/*

# Copy the Django requirements and install dependencies
COPY requirements.txt .    ## COPY takes two arguments, the file to be copied and the directory to copy it to.
RUN pip install --no-cache-dir -r requirements.txt   ## RUN is installing everything from the requirements.txt file

# Copy project files
COPY . .

# Run migrations and load fixtures
# RUN python manage.py migrate && python manage.py loaddata complete_backup.json

# Copy the Nginx configuration file to the directory listed
COPY nginx.conf /etc/nginx/nginx.conf

# Exposing ports from this container to the host, in this case NGINX will use these
EXPOSE 80 443

## CMD and entrypoint work together to start the container, ENTRYPOINT is run first, setting up the socialaccount.json fixture (but could also do
##  the nginx startup if desired), CMD is starting nginx and the django server gunicorn and binding it to port 8000
CMD service nginx start && gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000

ENTRYPOINT ["/app/entrypoint.sh"]
```

Entrypoint.sh

```
#!/bin/bash

## this creates the json file that will be loaded as an argument into loaddata during the command run on docker compose in the api service. ## socialaccount.json includes the environment variables $CLIENTID and $SECRETKEY that are used to log the user into github authentication

echo '[
    {
       "model": "sites.site",
       "pk": 1,
       "fields": {
          "domain": "learningplatform.com",
          "name": "Learning Platform"
       }
    },
    {
        "model": "socialaccount.socialapp",
        "pk": 1,
        "fields": {
            "provider": "github",
            "name": "Github",
            "client_id": "'"$CLIENTID"'",
            "secret": "'"$SECRETKEY"'",
            "key": "",
            "sites": [
                1
            ]
        }
    }
  ]
' > /app/LearningAPI/fixtures/socialaccount.json

# Run the default command
exec "$@"

```
